
include: package:lints/recommended.yaml

linter:
  rules:
    # Error rules
    - always_use_package_imports
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - empty_statements
    - hash_and_equals
    - no_duplicate_case_values
    - unrelated_type_equality_checks
    - valid_regexps

    # Style rules
    - always_declare_return_types
    - annotate_overrides
    - avoid_init_to_null
    - avoid_redundant_argument_values
    - avoid_return_types_on_setters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - camel_case_types
    - prefer_collection_literals
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_int_literals
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - sort_child_properties_last
    - unnecessary_const
    - unnecessary_new
    - unnecessary_this
    - use_key_in_widget_constructors

    # Pub rules
    - package_names
    - sort_pub_dependencies

analyzer:
  errors:
    # Treat missing required parameters as an error
    missing_required_param: error
    # Treat missing returns as an error
    missing_return: error
    # Treat using deprecated members as a warning
    deprecated_member_use: warning
    constant_identifier_names: ignore
    file_names: ignore
    avoid_function_literals_in_foreach_calls: ignore
    depend_on_referenced_packages: ignore
    curly_braces_in_flow_control_structures: ignore
    invalid_annotation_target: ignore
  exclude: ignore
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

# Uncomment the following lines for Flutter projects to exclude certain files
# exclude:
#   - "lib/generated_plugin_registrant.dart"