name: icoc_admin_pannel
description: "Admin panel for ICOC app."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_cloud_firestore: ^5.0.1
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.2.0
  get_it: ^7.7.0
  injectable: ^2.4.2
  intl: ^0.19.0
  logger: ^2.3.0
  http: ^1.2.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.3
  html: ^0.15.4
  youtube_player_iframe: ^5.0.0
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.3.1
  firebase_auth_web: ^5.12.4
  firebase_auth: ^5.1.2
  universal_html: ^2.2.4
  country_flags: ^3.0.0
  url_launcher: ^6.3.0
  json_annotation: ^4.9.0
  langchain_community: ^0.2.0+1
  langchain: ^0.7.1
  langchain_openai: ^0.6.1
  flutter_dotenv: ^5.1.0
  dartz: ^0.10.1
 
  

dev_dependencies:
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

  
flutter:
  generate: true
  uses-material-design: true



assets:
  - assets/
  # - .env