name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      
      # Set up Flutter
      - uses: subosito/flutter-action@v2

      # Run Flutter commands
      - run: flutter pub get # Install dependencies
      - run: flutter build web --dart-define=openAIKey=${{ secrets.openAIKey }} --web-renderer html

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ICOC_8F075 }}'
          channelId: live
          projectId: icoc-8f075
